### ISSUE TITLE
GET vs POST

### ISSUE THREAD

**Issue by KrijnHoetmer** [Duneyasaleh/buurtcampus_oost#4]
Probeer, zeker bij logins, altijd `method="POST"` te gebruiken. Zie ook https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods.

https://github.com/Duneyasaleh/duneya-web/blob/0a98add4c69afa666fe70fe176c71cc2bad464ca/resources/views/aanmelden.blade.php#L14

**Comment by Duneyasaleh** [comment]
https://github.com/Duneyasaleh/buurtcampus_oost/blob/5553b4f5cd886220bdf8c2a70f44111a5e77750e/resources/views/aanmelden.blade.php#L32

https://github.com/Duneyasaleh/buurtcampus_oost/blob/5553b4f5cd886220bdf8c2a70f44111a5e77750e/resources/views/aanmelden.blade.php#L14
